name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIN_MODE: test
      config: ../../cmd/config/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
        cache-dependency-path: |
              go.sum

    # - name: Run Unit Test
    #   run: go test ./test/... -json > TestResults-${{ github.sha }}.json

    # - name: Stop if tests fail
    #   if: ${{ failure() }}
    #   run: exit 1

    # - name: Upload Go test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Go-results-${{ github.sha }}
    #     path: TestResults-${{ github.sha }}.json

    - name: Build Go application
      working-directory: ./cmd
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o cloud-companion-agent .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      working-directory: ./cmd
      with:
        context: .
        file: Dockerfile  # Adjust the path to your Dockerfile
        push: true
        tags: |
          yohansutanto5/cloud-companion-agent:latest